services :
    database :
        image :          postgres
        container_name : database
        environment :
            POSTGRES_USER :     postgres
            POSTGRES_PASSWORD : root
            POSTGRES_DB :       jobflow
        ports :
        - 5432:5432
    application-server :
        image :          application-server:latest
        build :
            context :    back
            dockerfile : Dockerfile
        container_name : application-server
        ports :
        - 8080:8080
        depends_on :
        - database
        environment :
        - SERVER_PORT=8080
        - SPRING_DATASOURCE_URL=jdbc:postgresql://database/jobflow
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    web-server :
        image :          web-server:latest
        build :
            context :    front
            dockerfile : Dockerfile
        container_name : web-server
        ports :
        - 4200:4200
